### ISSUE TITLE
IllegalArgumentException - com.segment.analytics.reactnative.core.RNAnalyticsModule in identify at line 2

### ISSUE THREAD

**Issue by dgobaud** [segmentio/analytics-react-native#107]
```ts
import analytics from '@segment/analytics-react-native';
analytics.identify(null, { email });
```

```
java.lang.IllegalArgumentException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkParameterIsNotNull, parameter userId
    at com.segment.analytics.reactnative.core.RNAnalyticsModule.identify
    at java.lang.reflect.Method.invoke(Method.java)
    at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
    at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:158)
    at com.facebook.react.bridge.queue.NativeRunnable.run(NativeRunnable.java)
    at android.os.Handler.handleCallback(Handler.java:873)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:29)
    at android.os.Looper.loop(Looper.java:214)
    at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:232)
    at java.lang.Thread.run(Thread.java:764)
```

**Comment by aliasunder** [comment]
+1

**Comment by garfiaslopez** [comment]
+1

**Comment by ttuck303** [comment]
+1

**Comment by misterpoloy** [comment]
Same

**Comment by misterpoloy** [comment]
Can you try:
```
analytics.identify(() => ({}));
```

**Comment by vforvasile** [comment]
any workarounds?

**Comment by benjaminaudet** [comment]
Having the same problem.
Looks like there is a missing `?` in the generated native code on the userId parameter.

I've find a way to make it work : if user._id is falsy, '0' is passed
```
analytics.identify(
      user._id || '0',
      {
        ...user,
      },
    )
```

**Comment by bsneed** [comment]
Please reopen if this remains an issue.  Closing due to age.

**Comment by BogdanRad** [comment]
same problem.. how can I fix?

**Comment by amanolar** [comment]
Still same problem with version 1.5.0
