### ISSUE TITLE
identify crashes on Android: "java.lang.Double cannot be cast to java.lang.string"

### ISSUE THREAD

**Issue by ttuck303** [segmentio/analytics-react-native#123]
Works fine on iOS.
After identify, I get error: "java.lang.Double cannot be cast to java.lang.string".

Full error in logcat:
`2019-12-04 12:50:38.073 22964-23846/E/unknown:ReactNative: Exception in native call
    java.lang.ClassCastException: java.lang.Double cannot be cast to java.lang.String
        at com.facebook.react.bridge.ReadableNativeArray.getString(ReadableNativeArray.java:101)
        at com.facebook.react.bridge.JavaMethodWrapper$5.extractArgument(JavaMethodWrapper.java:73)
        at com.facebook.react.bridge.JavaMethodWrapper$5.extractArgument(JavaMethodWrapper.java:69)
        at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:359)
        at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:158)
        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
        at android.os.Handler.handleCallback(Handler.java:789)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:29)
        at android.os.Looper.loop(Looper.java:164)
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:232)
        at java.lang.Thread.run(Thread.java:764)`

js code:
`import Analytics from "@segment/analytics-react-native";`

`Analytics.setup(config.segment[Platform.OS], {
  trackAppLifecycleEvents: true
});`

`const identifyUserInSegment = profile => { 
  try {
    Analytics.identify(profile.id, { ...profile });
  } catch (err) {
    console.error("[segment] identify failed: ", err);
    console.error(err);
  }
};`

I have tried explicitly casting my arguments to string w/ JSON.stringify and passing a smaller attributes argument. 

"react-native": "0.60.4",
"@segment/analytics-react-native": "1.1.0",

Have tried manually linking as well as autolinking. 
Am also using redux, redux persist, braze (appboy), firebase, amplitude if any of these could be causing some kind of interference. 

Any help or ideas would be appreciated.

**Comment by ttuck303** [comment]
Needed to cast to string `toString()` and now it works
