### ISSUE TITLE
Error when adding the Mixpanel integration

### ISSUE THREAD

**Issue by davidimoore** [segmentio/analytics-react-native#146]
I've created a React Native [app](https://github.com/davidimoore/segment-test-app) to demonstrate this issue.

The following is a the result of running `yarn android`:

```
yarn run v1.16.0
$ react-native run-android
info Running jetifier to migrate libraries to AndroidX. You can disable it using "--no-jetifier" flag.
Jetifier found 880 file(s) to forward-jetify. Using 8 workers...
info JS server already running.
info Installing the app...

> Configure project :@segment_analytics-react-native
WARNING: The following project options are deprecated and have been removed: 
android.enableAapt2
This property has no effect, AAPT2 is now always used.

android.useDeprecatedNdk
NdkCompile is no longer supported



> Configure project :@segment_analytics-react-native-mixpanel
WARNING: The following project options are deprecated and have been removed: 
android.enableAapt2
This property has no effect, AAPT2 is now always used.

android.useDeprecatedNdk
NdkCompile is no longer supported



> Configure project :app
WARNING: The following project options are deprecated and have been removed: 
android.enableAapt2
This property has no effect, AAPT2 is now always used.

android.useDeprecatedNdk
NdkCompile is no longer supported



> Task :@segment_analytics-react-native:preBuild UP-TO-DATE
> Task :@segment_analytics-react-native:preDebugBuild UP-TO-DATE
> Task :@segment_analytics-react-native:checkDebugManifest UP-TO-DATE
> Task :@segment_analytics-react-native:generateDebugBuildConfig UP-TO-DATE
> Task :@segment_analytics-react-native:generateDebugResValues UP-TO-DATE
> Task :@segment_analytics-react-native:processDebugManifest UP-TO-DATE
> Task :@segment_analytics-react-native:prepareLintJar UP-TO-DATE
> Task :@segment_analytics-react-native-mixpanel:preBuild UP-TO-DATE
> Task :@segment_analytics-react-native-mixpanel:preDebugBuild UP-TO-DATE
> Task :@segment_analytics-react-native:packageDebugRenderscript NO-SOURCE
> Task :@segment_analytics-react-native-mixpanel:checkDebugManifest UP-TO-DATE
> Task :@segment_analytics-react-native-mixpanel:generateDebugBuildConfig UP-TO-DATE
> Task :@segment_analytics-react-native-mixpanel:generateDebugResValues UP-TO-DATE
> Task :@segment_analytics-react-native-mixpanel:processDebugManifest UP-TO-DATE
> Task :@segment_analytics-react-native-mixpanel:prepareLintJar UP-TO-DATE
> Task :@segment_analytics-react-native-mixpanel:compileDebugRenderscript NO-SOURCE
> Task :@segment_analytics-react-native:compileDebugAidl NO-SOURCE
> Task :@segment_analytics-react-native:compileDebugRenderscript NO-SOURCE
> Task :@segment_analytics-react-native:generateDebugResources UP-TO-DATE
> Task :@segment_analytics-react-native:packageDebugResources UP-TO-DATE
> Task :@segment_analytics-react-native:generateDebugRFile UP-TO-DATE
> Task :@segment_analytics-react-native:compileDebugKotlin UP-TO-DATE
> Task :@segment_analytics-react-native:generateDebugSources UP-TO-DATE
> Task :@segment_analytics-react-native:javaPreCompileDebug UP-TO-DATE
> Task :@segment_analytics-react-native:compileDebugJavaWithJavac UP-TO-DATE
> Task :@segment_analytics-react-native:bundleLibCompileDebug UP-TO-DATE
> Task :@segment_analytics-react-native-mixpanel:compileDebugAidl NO-SOURCE
> Task :@segment_analytics-react-native-mixpanel:generateDebugResources UP-TO-DATE
> Task :@segment_analytics-react-native-mixpanel:packageDebugResources UP-TO-DATE
> Task :@segment_analytics-react-native-mixpanel:generateDebugRFile UP-TO-DATE
> Task :@segment_analytics-react-native-mixpanel:compileDebugKotlin UP-TO-DATE
> Task :@segment_analytics-react-native-mixpanel:generateDebugSources UP-TO-DATE
> Task :@segment_analytics-react-native-mixpanel:javaPreCompileDebug UP-TO-DATE
> Task :@segment_analytics-react-native-mixpanel:compileDebugJavaWithJavac UP-TO-DATE
> Task :@segment_analytics-react-native-mixpanel:bundleLibCompileDebug UP-TO-DATE
> Task :app:generatePackageList
> Task :app:preBuild
> Task :app:preDebugBuild UP-TO-DATE
> Task :app:compileDebugAidl NO-SOURCE
> Task :@segment_analytics-react-native-mixpanel:packageDebugRenderscript NO-SOURCE
> Task :app:compileDebugRenderscript NO-SOURCE
> Task :app:checkDebugManifest UP-TO-DATE
> Task :app:generateDebugBuildConfig UP-TO-DATE
> Task :app:bundleDebugJsAndAssets SKIPPED
> Task :app:prepareLintJar UP-TO-DATE
> Task :app:generateDebugSources UP-TO-DATE
> Task :app:javaPreCompileDebug UP-TO-DATE
> Task :app:mainApkListPersistenceDebug UP-TO-DATE
> Task :app:generateDebugResValues UP-TO-DATE
> Task :app:generateDebugResources UP-TO-DATE
> Task :app:mergeDebugResources UP-TO-DATE
> Task :app:createDebugCompatibleScreenManifests UP-TO-DATE
> Task :app:processDebugManifest UP-TO-DATE
> Task :app:processDebugResources UP-TO-DATE
> Task :app:compileDebugJavaWithJavac UP-TO-DATE
> Task :@segment_analytics-react-native:mergeDebugShaders UP-TO-DATE
> Task :@segment_analytics-react-native:compileDebugShaders UP-TO-DATE
> Task :@segment_analytics-react-native:generateDebugAssets UP-TO-DATE
> Task :@segment_analytics-react-native:packageDebugAssets UP-TO-DATE
> Task :@segment_analytics-react-native-mixpanel:mergeDebugShaders UP-TO-DATE
> Task :@segment_analytics-react-native-mixpanel:compileDebugShaders UP-TO-DATE
> Task :@segment_analytics-react-native-mixpanel:generateDebugAssets UP-TO-DATE
> Task :@segment_analytics-react-native-mixpanel:packageDebugAssets UP-TO-DATE
> Task :app:mergeDebugShaders UP-TO-DATE
> Task :app:compileDebugShaders UP-TO-DATE
> Task :app:generateDebugAssets UP-TO-DATE
> Task :app:mergeDebugAssets UP-TO-DATE
> Task :app:copyDebugBundledJs SKIPPED
> Task :app:validateSigningDebug UP-TO-DATE
> Task :app:signingConfigWriterDebug UP-TO-DATE
> Task :@segment_analytics-react-native:bundleLibRuntimeDebug UP-TO-DATE
> Task :app:checkDebugDuplicateClasses FAILED

Deprecated Gradle features were used in this build, making it incompatible with Gradle 6.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/5.5/userguide/command_line_interface.html#sec:command_line_warnings
48 actionable tasks: 2 executed, 46 up-to-date

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:checkDebugDuplicateClasses'.
> 1 exception was raised by workers:
  java.lang.RuntimeException: java.lang.RuntimeException: Duplicate class com.segment.analytics.android.integrations.mixpanel.BuildConfig found in modules classes.jar (com.segment.analytics.android.integrations:mixpanel:2.3.0) and mixpanel-2.3.0.jar (com.segment.analytics.android.integrations:mixpanel:2.3.0)
  Duplicate class com.segment.analytics.android.integrations.mixpanel.MixpanelIntegration found in modules classes.jar (com.segment.analytics.android.integrations:mixpanel:2.3.0) and mixpanel-2.3.0.jar (com.segment.analytics.android.integrations:mixpanel:2.3.0)
  Duplicate class com.segment.analytics.android.integrations.mixpanel.MixpanelIntegration$1 found in modules classes.jar (com.segment.analytics.android.integrations:mixpanel:2.3.0) and mixpanel-2.3.0.jar (com.segment.analytics.android.integrations:mixpanel:2.3.0)
  
  Go to the documentation to learn how to <a href="d.android.com/r/tools/classpath-sync-errors">Fix dependency resolution errors</a>.


* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2s

Error: Command failed: ./gradlew app:installDebug -PreactNativeDevServerPort=8081

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:checkDebugDuplicateClasses'.
> 1 exception was raised by workers:
  java.lang.RuntimeException: java.lang.RuntimeException: Duplicate class com.segment.analytics.android.integrations.mixpanel.BuildConfig found in modules classes.jar (com.segment.analytics.android.integrations:mixpanel:2.3.0) and mixpanel-2.3.0.jar (com.segment.analytics.android.integrations:mixpanel:2.3.0)
  Duplicate class com.segment.analytics.android.integrations.mixpanel.MixpanelIntegration found in modules classes.jar (com.segment.analytics.android.integrations:mixpanel:2.3.0) and mixpanel-2.3.0.jar (com.segment.analytics.android.integrations:mixpanel:2.3.0)
  Duplicate class com.segment.analytics.android.integrations.mixpanel.MixpanelIntegration$1 found in modules classes.jar (com.segment.analytics.android.integrations:mixpanel:2.3.0) and mixpanel-2.3.0.jar (com.segment.analytics.android.integrations:mixpanel:2.3.0)
  
  Go to the documentation to learn how to <a href="d.android.com/r/tools/classpath-sync-errors">Fix dependency resolution errors</a>.


* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2s

    at checkExecSyncError (child_process.js:616:11)
    at execFileSync (child_process.js:634:13)
    at runOnAllDevices (/Users/david/sandbox/SegmentTestApp/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/runOnAllDevices.js:74:39)
    at buildAndRun (/Users/david/sandbox/SegmentTestApp/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/index.js:158:41)
    at then.result (/Users/david/sandbox/SegmentTestApp/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/index.js:125:12)
    at process._tickCallback (internal/process/next_tick.js:68:7)
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

```

**Comment by davidimoore** [comment]
I've confirmed the patches added to the segment and mixpanel libraries of the test app resolve the issue - https://github.com/davidimoore/segment-test-app/tree/fix/update-versions

**Comment by jeiemgi** [comment]
Hi @davidimoore  which version of segment and segment-mixpanel  includes this fix?

**Comment by davidimoore** [comment]
The libraries I'm attempting to install together in the linked app are
```
    "@segment/analytics-react-native": "^1.1.0",
    "@segment/analytics-react-native-mixpanel": "^1.1.0",
```

If you take a look at the patched [Segment Library](https://github.com/davidimoore/segment-test-app/blob/fix/update-versions/patches/%40segment%2Banalytics-react-native%2B1.1.0.patch#L58) and [Mixpanel](https://github.com/davidimoore/segment-test-app/blob/fix/update-versions/patches/%40segment%2Banalytics-react-native-mixpanel%2B1.1.0.patch#L59), the version numbers are changed from a range to a fixed number.

**Comment by bsneed** [comment]
this seems to be resolved from looking at the patch.  If that's not the case, please reopen this issue.

**Comment by isonlaxman** [comment]
I'm still facing this exact same issue. On seeing this Issue, I reverted to using the 1.1.0 versions, but I get the same error. 

Something to note: I'm using the Firebase integration library, not the Mixpanel one. Any guidance appreciated.
