### ISSUE TITLE
App Crashing on Firebase Testlab but working in physical device. java.lang.RuntimeException: Could not invoke RNAnalytics.setup

### ISSUE THREAD

**Issue by raveracker** [segmentio/analytics-react-native#262]
Hi,

I always have the app build test it in Firebase Testlab before pushing it to release. But on the pre-launch report of release I get error on almost 8 Devices with the same exception. The tested Android SDK Version is 28 and Device is Pixel2. Please let me know what this issue is and why is it coming up in pre-launch report.

Fatal exception
```
	at com.facebook.react.bridge.JavaModuleWrapper.invoke(Unknown Source:21)
     FATAL EXCEPTION: mqt_native_modules
Process: com.docmydoc, PID: 15046
java.lang.RuntimeException: Could not invoke RNAnalytics.setup
	at com.facebook.react.bridge.JavaMethodWrapper.invoke(Unknown Source:191)
	at com.facebook.react.bridge.JavaModuleWrapper.invoke(Unknown Source:21)
	at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(Unknown Source:0)
	at android.os.Looper.loop(Looper.java:193)
	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(Unknown Source:37)
	at java.lang.Thread.run(Thread.java:764)
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Method.invoke(Native Method)
	at com.facebook.react.bridge.JavaMethodWrapper.invoke(Unknown Source:147)
	... 8 more
Caused by: java.lang.IllegalAccessError: Interface androidx.lifecycle.c implemented by class com.segment.analytics.AnalyticsActivityLifecycleCallbacks is inaccessible (declaration of 'com.segment.analytics.AnalyticsActivityLifecycleCallbacks' appears in base.apk)
	at com.segment.analytics.a.<init>(Unknown Source:118)
	at com.segment.analytics.a$m.a(Unknown Source:333)
	at com.segment.analytics.reactnative.core.a.c(Unknown Source:27)
	at com.segment.analytics.reactnative.core.RNAnalyticsModule.setup(Unknown Source:202)
```

**Comment by raveracker** [comment]
Sorry, Got it resolved from [segmentio/analytics-android#735](https://github.com/segmentio/analytics-android/issues/735)
