### ISSUE TITLE
`analytics-react-native-appboy` crashes on start when installed together with `react-native-appboy-sdk`

### ISSUE THREAD

**Issue by abdullah-kasim** [segmentio/analytics-react-native#346]
As per the title, it looks like Braze needs another maven repo link (as per the Android docs: https://segment.com/docs/connections/destinations/catalog/braze/#android ).

This maven repo link, in particular: ` maven { url "http://appboy.github.io/appboy-segment-android/sdk" }`

Currently, without including this repo, `appboy-segment-integration` is stuck at version 7.0.0, and will crash with the latest `react-native-appboy-sdk` installed. Version 9.0.0 of `appboy-segment-integration` fixes this issue

EDIT: Also, looks like Braze's maven repository may be hit by this bug: https://github.com/Appboy/appboy-segment-android/issues/30 so a `+` version in gradle would only update `appboy-segment-integration` to `8.0.1`

Dependencies:

```
    "react-native-appboy-sdk": "^1.31.0",
    "@segment/analytics-react-native": "^1.5.0",
    "@segment/analytics-react-native-appboy": "^1.5.0",
    "@segment/analytics-react-native-appsflyer": "^1.5.0",
    "@segment/analytics-react-native-firebase": "^1.5.0",
    "@segment/analytics-react-native-mixpanel": "^1.5.0",
```

Crash log:

```
2021-08-11 18:35:00.746 15726-15726/com.myapp E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.myapp, PID: 15726
    java.lang.NoClassDefFoundError: Failed resolution of: Lcom/appboy/configuration/AppboyConfig$Builder;
        at com.segment.analytics.android.integrations.appboy.AppboyIntegration$1.create(AppboyIntegration.java:71)
        at com.segment.analytics.Analytics.performInitializeIntegrations(Analytics.java:1623)
        at com.segment.analytics.Analytics$2$1.run(Analytics.java:333)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:230)
        at android.app.ActivityThread.main(ActivityThread.java:7817)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:526)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1034)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.appboy.configuration.AppboyConfig$Builder" on path: DexPathList[[zip file "/data/app/com.myapp-aD96WO8JLbpBDsZZybIIYA==/base.apk"],nativeLibraryDirectories=[/data/app/com.myapp-aD96WO8JLbpBDsZZybIIYA==/lib/arm64, /data/app/com.myapp-aD96WO8JLbpBDsZZybIIYA==/base.apk!/lib/arm64-v8a, /system/lib64, /system/product/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:196)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass
```

**Comment by alanjcharles** [comment]
Hi @abdullah-kasim I'm not sure why you would need both `react-native-appboy-sdk` and `@segment/analytics-react-native-appboy". All the Segment package does [is pull in Braze's native SDKs ](https://github.com/segmentio/analytics-react-native/blob/master/packages/integrations/integrations.yml#L66)since we do not own this integration, [Braze does](https://segment.com/docs/connections/destinations/catalog/braze/). I would recommend removing the Braze package if you plan to implement with Segment and/or reach out to Braze for more support on this since they own the integrations. Closing for now but happy to reopen if you have other relevant issues/context I'm missing.

**Comment by faisal-vf** [comment]
@abdullah-kasim I was able to run everything successfully using `"react-native-appboy-sdk": "^1.32.0"` with `"@segment/analytics-react-native-appboy": "^1.5.0"`. 

In build.gradle: 

```
maven { url "https://appboy.github.io/appboy-android-sdk/sdk" }
maven { url "http://appboy.github.io/appboy-segment-android/sdk" }
```

I know it doesn't answer your question but hope it helps.

**Comment by abdullah-kasim** [comment]
No worries, I've resolved this issue myself before I reported this issue through the same way as you did.

Appreciate putting the solution in here though, that should help others.

**Comment by glennweb** [comment]
Yeah, @faisal-vf solution solved for me!
