### ISSUE TITLE
Could not resolve all artifacts for configuration ':segment_analytics-react-native:classpath'

### ISSUE THREAD

**Issue by clinton15** [segmentio/analytics-react-native#473]
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':segment_analytics-react-native'.
> Could not resolve all artifacts for configuration ':segment_analytics-react-native:classpath'.
   > Could not resolve com.android.tools.build:gradle:3.1.4.
     Required by:
         project :segment_analytics-react-native
      > Could not resolve com.android.tools.build:gradle:3.1.4.
         > Could not get resource 'https://maven.google.com/com/android/tools/build/gradle/3.1.4/gradle-3.1.4.pom'.
            > Could not HEAD 'https://maven.google.com/com/android/tools/build/gradle/3.1.4/gradle-3.1.4.pom'.
               > The server may not support the client's requested TLS protocol versions: (TLSv1.2, TLSv1.3). You may need to configure the client to allow other p
rotocols to be used. See: https://docs.gradle.org/7.2/userguide/build_environment.html#gradle_system_properties
                  > sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to fin
d valid certification path to requested target

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 30s

    at makeError (D:\test_app\node_modules\execa\index.js:174:9)
    at D:\test_app\node_modules\execa\index.js:278:16
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async runOnAllDevices (D:\test_app\node_modules\@react-native-community\cli-platform-android\build\commands\runAndroid\runOnAllDevices.js:109:5)
    at async Command.handleAction (D:\test_app\node_modules\react-native\node_modules\@react-native-community\cli\build\index.js:192:9)
info Run CLI with --verbose flag for more details.

- `analytics-react-native` version: 1.5.2
- Integrations versions (if used):
- React Native version:
- iOS or Android or both?

**Steps to reproduce**

**Expected behavior**

**Actual behavior**

**Comment by stevekeol** [comment]
Me too. How can i fix it ? Is there anybody help me?

**Comment by clinton15** [comment]
@stevekeol I found a temporary solution:
adding google() in \node_modules\@segment\analytics-react-native\android\build.gradle fixed this issue for me

the code snippet will look like this:
buildscript {
    ext.defaultKotlinVersion = '1.4.0'

    repositories {
        google()
        jcenter()
        maven { url 'https://maven.google.com' }
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.1.4'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:${rootProject.ext.has("kotlinVersion") ? rootProject.ext.get("kotlinVersion") : defaultKotlinVersion}"
    }
}

**Comment by alanjcharles** [comment]
@clinton15  @stevekeol  versions of `analytics-react-native  > 2.0.0` do not support `react-native 0.67.3`, I'm afraid. We currently do not have plans to do any additional work on those versions and instead, recommend updating to our latest in order to successfully build on newer versions of react native. You can find the [migration guide here](https://github.com/segmentio/analytics-react-native/blob/master/MIGRATION_GUIDE.md). Please feel free to reach out to friends@segment.com with any additional questions.
