### ISSUE TITLE
Android kotlin runtime error

### ISSUE THREAD

**Issue by sondremare** [segmentio/analytics-react-native#62]
I am having trouble using this library on Android. 
I am currently running React-Native 0.57.8, and therefor using version 0.0.1-beta.3 of this library. 
This is the last version before RN 0.59 support was added.

I am getting the following error:

```
java.lang.NoClassDefFoundError: Failed resolution of: Lkotlin/jvm/internal/Intrinsics;
at com.segment.analytics.reactnative.core.RNAnalyticsPackage.createViewManagers(RNAnalyticsPackage.kt)
at com.facebook.react.ReactInstanceManager.getOrCreateViewManagers(ReactInstanceManager.java:756)
at com.facebook.react.CoreModulesPackage.createUIManager(CoreModulesPackage.java:170)
at com.facebook.react.CoreModulesPackage.access$200(CoreModulesPackage.java:53)
at com.facebook.react.CoreModulesPackage$7.get(CoreModulesPackage.java:128)
at com.facebook.react.CoreModulesPackage$7.get(CoreModulesPackage.java:125)
at com.facebook.react.NativeModuleRegistryBuilder.processPackage(NativeModuleRegistryBuilder.java:61)
at com.facebook.react.ReactInstanceManager.processPackage(ReactInstanceManager.java:1173)
at com.facebook.react.ReactInstanceManager.processPackages(ReactInstanceManager.java:1143)
at com.facebook.react.ReactInstanceManager.createReactContext(ReactInstanceManager.java:1085)
at com.facebook.react.ReactInstanceManager.access$900(ReactInstanceManager.java:117)
at com.facebook.react.ReactInstanceManager$5.run(ReactInstanceManager.java:916)
at java.lang.Thread.run(Thread.java:761)
Caused by: java.lang.ClassNotFoundException: Didn't find class "kotlin.jvm.internal.Intrinsics" on path: DexPathList[[zip file "/data/app/com.xxx/base.apk"],nativeLibraryDirectories=[/data/app/com.xxx/lib/x86, /data/app/com.xxx/base.apk!/lib/x86, /system/lib, /vendor/lib]]
at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
at java.lang.ClassLoader.loadClass(ClassLoader.java:312)

```

My settings.gradle file contains this:
```
include ':@segment/analytics-react-native'
project(':@segment/analytics-react-native').projectDir = new File(rootProject.projectDir, '../node_modules/@segment/analytics-react-native/android')
```

My app/build.gradle file contains this:
```

compile project(path: ':@segment/analytics-react-native', configuration: 'default')
```

Setting the configuration to 'default' as I would otherwise get a build-time error because the kotlin-plugin adds a null value to the candidate set AttributeDisambiguationRule (read more: https://github.com/gradle/gradle/issues/6747)

I am currently using Gradle 4.4, with Gradle Build tools at 3.1.4

And as you might discern from the error stacktrace, I have multiDexEnabled

PS! I have also tried version 0.1.0-beta.0, but to no avail

**Comment by AmitPandya007** [comment]
check your kotlin versions in build.gradle files in all dependencies which you have added.
Upgrade them to latest version i.e. 
`classpath 'org.jetbrains.kotlin:kotlin-gradle-plugin:1.3.21'
`and upgrade the gradle version too:
`classpath 'com.android.tools.build:gradle:3.4.2'`
